### ISSUE TITLE
Provide a license

### ISSUE THREAD

**Issue by jdsika** [GAIA-X4PLC-AAD/ssi-to-oidc-bridge#3]
# todos

- [x] Create LICENSE file in root, don't forget copyright notice
- [x] Recommended license is "MIT"
- [x] Set SPDX license header
