### ISSUE TITLE
Create tags and releases

### ISSUE THREAD

**Issue by jdsika** [GAIA-X4PLC-AAD/ssi-to-oidc-bridge#4]
# Todos

[release docu](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases)

- [x] Merge MVP 1 into main
- [x] Add tag rule [here](https://github.com/GAIA-X4PLC-AAD/ssi-to-oidc-bridge/settings/tag_protection)
- [x] Create "tag" Swiss Conference v0.0.1
- [x] Merge main into dev because of the additional merge commit
- [x] Merge dev into main
- [x] Create release tag v1.0.0
- [x] delete old branches
