### ISSUE TITLE
GH Actions

### ISSUE THREAD

**Issue by jdsika** [GAIA-X4PLC-AAD/ssi-to-oidc-bridge#6]
# Todos

- [x] Run linter action
- [x] Run unit-test action
- [x] Run build action
- [ ] Optional: docker action
- [x] Use clear naming for actions
- [x] Add actions to branch protection rules for main branch
- [x] Add CI batch to readme

**Comment by jfelixh** [comment]
Done and live on main.
